services:
  terraform:
    profiles: [dummy]
    image: hashicorp/terraform:1.9.4
    environment:
      - TF_LOG
      - TF_CLI_ARGS
    volumes:
      - ./example-terraform:/workspace
    working_dir: /workspace
